// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CharacterCard: typeof import('./src/components/commons/CharacterCard.vue')['default']
    Close: typeof import('./src/components/icons/close.vue')['default']
    Dashboard: typeof import('./src/components/Dashboard.vue')['default']
    DeleteUserModal: typeof import('./src/components/DeleteUserModal.vue')['default']
    Footer: typeof import('./src/components/layout/Footer/index.vue')['default']
    FormListBox: typeof import('./src/components/FormListBox.vue')['default']
    Grid: typeof import('./src/components/Grid.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    InputFile: typeof import('./src/components/InputFile.vue')['default']
    InputFiles: typeof import('./src/components/InputFiles.vue')['default']
    ListBox: typeof import('./src/components/ListBox.vue')['default']
    ListExperiment: typeof import('./src/components/ListExperiment.vue')['default']
    LoaderSpinner: typeof import('./src/components/commons/LoaderSpinner.vue')['default']
    LoadingSpinner: typeof import('./src/components/LoadingSpinner.vue')['default']
    ManualProcessModal: typeof import('./src/components/ManualProcessModal.vue')['default']
    MiniChartPie: typeof import('./src/components/MiniChartPie.vue')['default']
    Modal: typeof import('./src/components/commons/Modal.vue')['default']
    Navbar: typeof import('./src/components/layout/Navbar/index.vue')['default']
    Pagination: typeof import('./src/components/commons/Pagination.vue')['default']
    ReturnToSupplierModal: typeof import('./src/components/ReturnToSupplierModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RouterViewTransition: typeof import('./src/components/RouterViewTransition.vue')['default']
    SearchBox: typeof import('./src/components/SearchBox.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    SidebarAdmin: typeof import('./src/components/SidebarAdmin.vue')['default']
    SidebarSupplier: typeof import('./src/components/SidebarSupplier.vue')['default']
    SkeletonCard: typeof import('./src/components/commons/SkeletonCard.vue')['default']
    SortController: typeof import('./src/components/SortController.vue')['default']
    TemplatesGrid: typeof import('./src/components/TemplatesGrid.vue')['default']
    ToastNotification: typeof import('./src/components/ToastNotification.vue')['default']
    Tree: typeof import('./src/components/Tree.vue')['default']
    TreeNode: typeof import('./src/components/TreeNode.vue')['default']
    WebViewer: typeof import('./src/components/WebViewer.vue')['default']
    WkWindow: typeof import('./src/components/wkWindow.vue')['default']
  }
}
